CREATE TABLE Trains(
  ID INT PRIMARY KEY,
  TRAIN_NUM INT
);

CREATE TABLE TrainSchedule(
  ID INT PRIMARY KEY,
  TRAIN_ID INT,
  SCHEDULE_ID INT
);

CREATE TABLE StationSchedule(
  ID INT PRIMARY KEY,
  STATION_ID INT,
  ARRIVAL_TIME TEXT,
  DEPARTURE_TIME TEXT
);

CREATE TABLE Stations (
  ID TEXT PRIMARY KEY,
  STATION_NAME TEXT
);
