CREATE TABLE Trains(
  ID INT PRIMARY KEY,
  TRAIN_NUM INT
);

CREATE TABLE TrainSchedule(
  ID INT PRIMARY KEY,
  TRAIN_ID INT,
  SCHEDULE_ID TEXT
);

CREATE TABLE StationSchedule(
  ID INT PRIMARY KEY,
  STATION_ID_D TEXT,
  STATION_ID_A TEXT,
  DEPARTURE_TIME INT,
  ARRIVAL_TIME INT
);

CREATE TABLE Stations (
  ID TEXT PRIMARY KEY,
  STATION_NAME TEXT
);
